#!/usr/bin/env python3
"""
Phase 2 — Masked SFT training with FSDP (ZeRO-3 sharding) across 4 GPUs.

FSDP shards model params, gradients, AND optimizer states across GPUs.
For Qwen3-4B on 4x48GB:
  - Each GPU holds ~2GB of params (1/4 of 8GB)
  - Optimizer states also sharded → very low per-GPU memory
  - Can run larger batch sizes than DDP

Run with:
    torchrun --nproc_per_node=4 train_fkl_fsdp.py \
        --input      datasets/wildchat/y_star.jsonl \
        --output_dir ./checkpoints \
        --model      Qwen/Qwen3-4B
"""

import argparse
import json
import os
from functools import partial
from pathlib import Path

import torch
import torch.distributed as dist
from torch.distributed.fsdp import (
    BackwardPrefetch,
    FullyShardedDataParallel as FSDP,
    MixedPrecision,
    ShardingStrategy,
)
from torch.distributed.fsdp import FullStateDictConfig, StateDictType
from torch.distributed.fsdp.wrap import transformer_auto_wrap_policy
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset, DistributedSampler
from transformers import AutoModelForCausalLM, AutoTokenizer, get_cosine_schedule_with_warmup
from tqdm import tqdm

try:
    import bitsandbytes as bnb
    HAS_BNB = True
except ImportError:
    HAS_BNB = False

try:
    import wandb
    HAS_WANDB = True
except ImportError:
    HAS_WANDB = False


# ─────────────────────────────────────────────────────────────
# Distributed helpers
# ─────────────────────────────────────────────────────────────

def setup():
    dist.init_process_group("nccl")
    rank       = int(os.environ["RANK"])
    local_rank = int(os.environ["LOCAL_RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    torch.cuda.set_device(local_rank)
    return rank, local_rank, world_size


def cleanup():
    dist.destroy_process_group()


def is_main(rank: int) -> bool:
    return rank == 0


# ─────────────────────────────────────────────────────────────
# Dataset
# ─────────────────────────────────────────────────────────────

class FKLDataset(Dataset):
    """
    Student input:  x (prompt only — no GPT-4 y, no follow-up o)
    Student target: y* (generated by teacher Qwen conditioned on x,y,o)
    Labels:         -100 for prompt tokens, actual ids for y* tokens
    """

    def __init__(self, path: str, tokenizer, max_length: int, rank: int):
        self.tokenizer  = tokenizer
        self.max_length = max_length
        self.items      = self._load(path, rank)

    def _load(self, path: str, rank: int) -> list:
        raw = []
        with open(path) as f:
            for line in f:
                if line.strip():
                    raw.append(json.loads(line))

        items   = []
        skipped = 0
        for item in tqdm(raw, desc="Tokenizing", disable=not is_main(rank)):
            # Prompt: x only
            prompt_text = self.tokenizer.apply_chat_template(
                item["x"],
                tokenize=False,
                add_generation_prompt=True,
            )
            # Full sequence: x + y*
            full_text = self.tokenizer.apply_chat_template(
                list(item["x"]) + [item["y_star"]],
                tokenize=False,
                add_generation_prompt=False,
            )

            prompt_ids = self.tokenizer(prompt_text, add_special_tokens=False)["input_ids"]
            full_enc   = self.tokenizer(
                full_text,
                add_special_tokens=False,
                truncation=True,
                max_length=self.max_length,
            )

            input_ids  = full_enc["input_ids"]
            prompt_len = len(prompt_ids)

            # Labels: mask prompt, keep y* tokens
            labels = [-100] * len(input_ids)
            if prompt_len < len(input_ids):
                labels[prompt_len:] = input_ids[prompt_len:]

            # Skip samples where y* was truncated away entirely
            if all(l == -100 for l in labels):
                skipped += 1
                continue

            items.append({
                "input_ids": torch.tensor(input_ids, dtype=torch.long),
                "labels":    torch.tensor(labels,    dtype=torch.long),
            })

        if is_main(rank):
            print(f"[Dataset] {len(items)} usable, {skipped} skipped (y* truncated)")
        return items

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        return self.items[idx]


def collate(batch: list, pad_id: int) -> dict:
    """Right-pad to longest sequence. Labels padded with -100."""
    input_ids = torch.nn.utils.rnn.pad_sequence(
        [x["input_ids"] for x in batch], batch_first=True, padding_value=pad_id
    )
    labels = torch.nn.utils.rnn.pad_sequence(
        [x["labels"] for x in batch], batch_first=True, padding_value=-100
    )
    return {
        "input_ids":      input_ids,
        "attention_mask": input_ids.ne(pad_id),
        "labels":         labels,
    }


# ─────────────────────────────────────────────────────────────
# Loss — single forward pass
# ─────────────────────────────────────────────────────────────

def masked_fkl_loss(
    model,
    input_ids:      torch.Tensor,
    attention_mask: torch.Tensor,
    labels:         torch.Tensor,
    mask_tau:       float,
):
    """
    Single forward pass:
      1. Forward → logits (gradient graph lives here)
      2. Detach logits → compute mask (no graph needed)
      3. log_softmax on live logits → loss (grad flows through)

    Mask: m_i = 1 if pi_theta(y*_i | x, y*_{<i}) >= mask_tau
    Loss: -sum(m_i * log_prob_i) / sum(m_i)
    """
    target_mask = labels != -100  # (B, T)

    # Single FSDP forward — gradient graph lives here
    logits = model(input_ids=input_ids, attention_mask=attention_mask).logits  # (B, T, V)

    # Shift: logits[t] predicts position t+1
    shifted_logits      = logits[:, :-1, :].contiguous()   # (B, T-1, V)
    shifted_labels      = labels[:, 1:].contiguous()        # (B, T-1)
    shifted_target_mask = target_mask[:, 1:]                # (B, T-1)

    # Safe labels for gather — replace -100 with 0 at non-target positions
    safe_labels = shifted_labels.clone()
    safe_labels[~shifted_target_mask] = 0

    # ── Mask: detach so no gradient flows through this ────────────────
    with torch.no_grad():
        probs       = torch.softmax(shifted_logits.detach(), dim=-1)
        token_probs = probs.gather(-1, safe_labels.unsqueeze(-1)).squeeze(-1)
        prob_mask   = (token_probs >= mask_tau) & shifted_target_mask  # (B, T-1)

    # ── Loss: grad flows through log_softmax(shifted_logits) ──────────
    log_probs       = torch.log_softmax(shifted_logits, dim=-1)
    token_log_probs = log_probs.gather(-1, safe_labels.unsqueeze(-1)).squeeze(-1)

    masked_log_probs = prob_mask.float() * token_log_probs
    denom            = prob_mask.float().sum().clamp(min=1e-8)
    loss             = -masked_log_probs.sum() / denom

    return loss, prob_mask.float().mean().item()


# ─────────────────────────────────────────────────────────────
# Checkpoint saving — FSDP requires special handling
# ─────────────────────────────────────────────────────────────

def save_checkpoint(model, tokenizer, path: str, rank: int, base_model_name: str):
    """
    FSDP full state dict save:
      - All ranks participate in gathering the full state dict
      - Only rank 0 writes to disk
      - offload_to_cpu=True keeps GPU memory free during gather
    """
    dist.barrier()  # sync all ranks before saving

    save_policy = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
    with FSDP.state_dict_type(model, StateDictType.FULL_STATE_DICT, save_policy):
        state_dict = model.state_dict()

    if is_main(rank):
        os.makedirs(path, exist_ok=True)
        # Load a fresh model shell and inject the gathered state dict
        save_model = AutoModelForCausalLM.from_pretrained(
            base_model_name,
            torch_dtype=torch.bfloat16,
        )
        save_model.load_state_dict(state_dict)
        save_model.save_pretrained(path)
        tokenizer.save_pretrained(path)
        print(f"\n[Saved] {path}")
        del save_model

    dist.barrier()  # wait for rank 0 to finish writing


# ─────────────────────────────────────────────────────────────
# Training loop
# ─────────────────────────────────────────────────────────────

def train(model, tokenizer, dataset, args, rank, local_rank, world_size):
    sampler = DistributedSampler(dataset, num_replicas=world_size, rank=rank, shuffle=True)
    loader  = DataLoader(
        dataset,
        batch_size=args.batch_size,
        sampler=sampler,
        collate_fn=lambda b: collate(b, tokenizer.pad_token_id),
        num_workers=4,
        pin_memory=True,
        persistent_workers=True,
    )

    # With FSDP, optimizer states are sharded — 8-bit less critical but still saves memory
    if args.optimizer == "adamw_8bit" and HAS_BNB:
        optimizer = bnb.optim.AdamW8bit(model.parameters(), lr=args.lr, weight_decay=0.01)
    else:
        if args.optimizer == "adamw_8bit" and not HAS_BNB:
            if is_main(rank):
                print("[WARN] bitsandbytes not found, falling back to AdamW")
        optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=0.01)

    total_steps  = (len(loader) * args.epochs) // args.grad_accum
    warmup_steps = int(0.05 * total_steps)
    scheduler    = get_cosine_schedule_with_warmup(optimizer, warmup_steps, total_steps)

    if is_main(rank) and HAS_WANDB and not args.no_wandb:
        wandb.init(project=args.wandb_project, name=args.run_name, config=vars(args))

    if is_main(rank):
        print(f"Steps/epoch: {len(loader)}  |  Total steps: {total_steps}")
        print(f"Effective batch: {args.batch_size} × {world_size} GPUs × {args.grad_accum} accum = "
              f"{args.batch_size * world_size * args.grad_accum}")

    global_step = 0
    for epoch in range(args.epochs):
        sampler.set_epoch(epoch)
        model.train()
        optimizer.zero_grad()

        pbar = tqdm(loader, desc=f"Epoch {epoch+1}/{args.epochs}", disable=not is_main(rank))
        for step, batch in enumerate(pbar):
            # Move to local GPU — use local_rank not rank for device
            input_ids      = batch["input_ids"].to(local_rank)
            attention_mask = batch["attention_mask"].to(local_rank)
            labels         = batch["labels"].to(local_rank)

            loss, mask_density = masked_fkl_loss(
                model, input_ids, attention_mask, labels, args.mask_tau
            )
            (loss / args.grad_accum).backward()

            if (step + 1) % args.grad_accum == 0:
                # FSDP has its own clip_grad_norm_ that works across shards
                model.clip_grad_norm_(1.0)
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()
                global_step += 1

                if is_main(rank):
                    lr = scheduler.get_last_lr()[0]
                    pbar.set_postfix({
                        "loss":  f"{loss.item():.4f}",
                        "mask":  f"{mask_density:.2f}",
                        "lr":    f"{lr:.1e}",
                    })
                    if HAS_WANDB and not args.no_wandb:
                        wandb.log({
                            "loss":         loss.item(),
                            "mask_density": mask_density,
                            "lr":           lr,
                            "global_step":  global_step,
                        })
                    if mask_density < 0.1:
                        print(f"\n[WARN] mask_density={mask_density:.3f} — check --mask_tau")

                # Checkpoint every N steps — all ranks must call save_checkpoint together
                if global_step % args.save_steps == 0:
                    save_checkpoint(
                        model, tokenizer,
                        os.path.join(args.output_dir, f"step-{global_step}"),
                        rank, args.model,
                    )
                    model.train()  # restore train mode after save

    # Final save
    save_checkpoint(
        model, tokenizer,
        os.path.join(args.output_dir, "final"),
        rank, args.model,
    )
    if is_main(rank):
        print("Training complete.")


# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("--input",       required=True)
    parser.add_argument("--output_dir",  default="./checkpoints")
    parser.add_argument("--model",       default="Qwen/Qwen3-4B")

    # With FSDP ZeRO-3, params are sharded so each GPU holds ~2GB of the 8GB model.
    # Can safely run larger batches than DDP.
    # 4x48GB: batch_size=32 per GPU → effective batch = 128
    parser.add_argument("--batch_size",  type=int,   default=32)
    parser.add_argument("--grad_accum",  type=int,   default=1)
    parser.add_argument("--epochs",      type=int,   default=2)
    parser.add_argument("--lr",          type=float, default=2e-6)
    parser.add_argument("--optimizer",   type=str,   default="adamw_8bit", choices=["adamw", "adamw_8bit"])
    parser.add_argument("--max_length",  type=int,   default=2048)
    parser.add_argument("--mask_tau",    type=float, default=0.001)
    parser.add_argument("--save_steps",  type=int,   default=500)

    parser.add_argument("--wandb_project", default="fkl-distill-fsdp")
    parser.add_argument("--run_name",      default=None)
    parser.add_argument("--no_wandb",      action="store_true")

    args = parser.parse_args()
    rank, local_rank, world_size = setup()
    os.makedirs(args.output_dir, exist_ok=True)

    if is_main(rank):
        print(f"=== FKL FSDP Training ===")
        print(f"World size: {world_size}  |  Model: {args.model}")

    # Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    tokenizer.padding_side = "right"  # right-pad for causal LM label alignment
    if tokenizer.pad_token is None:
        tokenizer.pad_token    = tokenizer.eos_token
        tokenizer.pad_token_id = tokenizer.eos_token_id

    # Dataset
    dataset = FKLDataset(args.input, tokenizer, args.max_length, rank)

    # Load model on CPU first — FSDP will shard it across GPUs
    if is_main(rank):
        print("Loading model on CPU (FSDP will shard to GPUs)...")
    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        torch_dtype=torch.bfloat16,
        attn_implementation="sdpa",  # sdpa is more stable with FSDP than flash_attn
    )

    # Enable gradient checkpointing to save activation memory
    model.gradient_checkpointing_enable()

    # ── FSDP wrapping ─────────────────────────────────────────────────
    # Detect the transformer layer class for wrapping
    # Qwen3 uses Qwen3DecoderLayer
    try:
        from transformers.models.qwen3.modeling_qwen3 import Qwen3DecoderLayer
        layer_cls = {Qwen3DecoderLayer}
    except ImportError:
        try:
            from transformers.models.qwen2.modeling_qwen2 import Qwen2DecoderLayer
            layer_cls = {Qwen2DecoderLayer}
        except ImportError:
            # Fallback: wrap any nn.Module with >1M params
            from torch.distributed.fsdp.wrap import size_based_auto_wrap_policy
            layer_cls = None

    if layer_cls is not None:
        wrap_policy = partial(
            transformer_auto_wrap_policy,
            transformer_layer_cls=layer_cls,
        )
    else:
        wrap_policy = partial(size_based_auto_wrap_policy, min_num_params=1_000_000)

    model = FSDP(
        model,
        auto_wrap_policy=wrap_policy,
        mixed_precision=MixedPrecision(
            param_dtype=torch.bfloat16,
            reduce_dtype=torch.bfloat16,
            buffer_dtype=torch.bfloat16,
        ),
        sharding_strategy=ShardingStrategy.FULL_SHARD,   # ZeRO-3: shards params+grads+optimizer
        device_id=torch.cuda.current_device(),
        sync_module_states=True,                         # Sync weights from rank 0 to all GPUs
        backward_prefetch=BackwardPrefetch.BACKWARD_PRE,  # prefetch next layer while computing current
        limit_all_gathers=True,                           # prevents OOM from too many in-flight all-gathers
    )

    if is_main(rank):
        print("FSDP model ready.")

    train(model, tokenizer, dataset, args, rank, local_rank, world_size)
    cleanup()


if __name__ == "__main__":
    main()